config/routes.php
<?php
/**
 * Routes configuration.
 *
 * In this file, you set up routes to your controllers and their actions.
 * Routes are very important mechanism that allows you to freely connect
 * different URLs to chosen controllers and their actions (functions).
 *
 * It's loaded within the context of `Application::routes()` method which
 * receives a `RouteBuilder` instance `$routes` as method argument.
 *
 * CakePHP(tm) : Rapid Development Framework (https://cakephp.org)
 * Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
 *
 * Licensed under The MIT License
 * For full copyright and license information, please see the LICENSE.txt
 * Redistributions of files must retain the above copyright notice.
 *
 * @copyright     Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
 * @link          https://cakephp.org CakePHP(tm) Project
 * @license       https://opensource.org/licenses/mit-license.php MIT License
 */

use Cake\Http\Middleware\CsrfProtectionMiddleware;
use Cake\Routing\Route\DashedRoute;
use Cake\Routing\RouteBuilder;

/*
 * The default class to use for all routes
 *
 * The following route classes are supplied with CakePHP and are appropriate
 * to set as the default:
 *
 * - Route
 * - InflectedRoute
 * - DashedRoute
 *
 * If no call is made to `Router::defaultRouteClass()`, the class used is
 * `Route` (`Cake\Routing\Route\Route`)
 *
 * Note that `Route` does not do any inflections on URLs which will result in
 * inconsistently cased URLs when used with `:plugin`, `:controller` and
 * `:action` markers.
 */
/** @var \Cake\Routing\RouteBuilder $routes */
$routes->setRouteClass(DashedRoute::class);

$routes->scope('/', function (RouteBuilder $builder) {
    // Register scoped middleware for in scopes.
    // $builder->registerMiddleware('csrf', new CsrfProtectionMiddleware([
    //     'httponly' => true,
    // ]));

    /*
     * Apply a middleware to the current route scope.
     * Requires middleware to be registered through `Application::routes()` with `registerMiddleware()`
     */
    // kita gunain csrf di Application.php
    // $builder->applyMiddleware('csrf');

    /*
     * Here, we are connecting '/' (base path) to a controller called 'Pages',
     * its action called 'display', and we pass a param to select the view file
     * to use (in this case, templates/Pages/home.php)...
     */
    // $builder->connect('/', ['controller' => 'Pages', 'action' => 'display', 'home']);
    $builder->connect('/', ['controller' => 'Dashboards', 'action' => 'index', 'home']);

    /*
     * ...and connect the rest of 'Pages' controller's URLs.
     */
    $builder->connect('/pages/*', ['controller' => 'Pages', 'action' => 'display']);

    /*
     * Connect catchall routes for all controllers.
     *
     * The `fallbacks` method is a shortcut for
     *
     * ```
     * $builder->connect('/:controller', ['action' => 'index']);
     * $builder->connect('/:controller/:action/*', []);
     * ```
     *
     * You can remove these routes once you've connected the
     * routes you want in your application.
     */
    
    $builder->setExtensions(['json', 'xml']);

    $builder->fallbacks();
});

/*
 * If you need a different set of middleware or none at all,
 * open new scope and define routes there.
 *
 * ```
 * $routes->scope('/api', function (RouteBuilder $builder) {
 *     // No $builder->applyMiddleware() here.
 *     // Connect API actions here.
 * });
 * ```
 */

src/Model/Entity/Job.php
<?php
declare(strict_types=1);

namespace App\Model\Entity;

use Cake\ORM\Entity;

/**
 * Job Entity
 *
 * @property int $id
 * @property int|null $job_type_id
 * @property int|null $job_status_id
 * @property int|null $user_id
 * @property int|null $product_id
 * @property int|null $customer_id
 * @property int|null $is_urgent
 * @property \Cake\I18n\FrozenTime|null $date
 * @property \Cake\I18n\FrozenTime|null $created
 * @property \Cake\I18n\FrozenTime|null $modified
 *
 * @property \App\Model\Entity\JobType $job_type
 * @property \App\Model\Entity\JobStatus $job_status
 * @property \App\Model\Entity\User[] $users
 * @property \App\Model\Entity\Product $product
 * @property \App\Model\Entity\Customer $customer
 */
class Job extends Entity
{
    /**
     * Fields that can be mass assigned using newEntity() or patchEntity().
     *
     * Note that when '*' is set to true, this allows all unspecified fields to
     * be mass assigned. For security purposes, it is advised to set '*' to false
     * (or remove it), and explicitly make individual fields accessible as needed.
     *
     * @var array
     */
    protected $_accessible = [
        'service_id' => true,
        'job_type_id' => true,
        'job_statuses_id' => true,
        'user_id' => true,
        'product_id' => true,
        'customer_id' => true,
        'is_urgent' => true,
        'date' => true,
        'created' => true,
        'modified' => true,
        'job_type' => true,
        'job_status' => true,
        'users' => true,
        'product' => true,
        'customer' => true,
    ];
    protected $_virtual = ['job_type_with_product_name'];
    protected function _getJobTypeWithProductName()
    {
        $defaultValue   =   null;

        if(isset($this->job_type->name) && isset($this->product->name)) {
            $defaultValue   =   $this->job_type->name . " for " . $this->product->name;
        } else {
            $defaultValue   =   " ";
        }

        return $defaultValue;

    }

}

src/Model/Entity/JobType.php
<?php
declare(strict_types=1);

namespace App\Model\Entity;

use Cake\ORM\Entity;

/**
 * JobType Entity
 *
 * @property int $id
 * @property string|null $name
 * @property string|null $desc
 *
 * @property \App\Model\Entity\Job[] $jobs
 */
class JobType extends Entity
{
    /**
     * Fields that can be mass assigned using newEntity() or patchEntity().
     *
     * Note that when '*' is set to true, this allows all unspecified fields to
     * be mass assigned. For security purposes, it is advised to set '*' to false
     * (or remove it), and explicitly make individual fields accessible as needed.
     *
     * @var array
     */
    protected $_accessible = [
        'name' => true,
        'desc' => true,
        'jobs' => true,
    ];
}

src/Model/Table/JobsTable.php
<?php
declare(strict_types=1);

namespace App\Model\Table;

use Cake\ORM\Query;
use Cake\ORM\RulesChecker;
use Cake\ORM\Table;
use Cake\Validation\Validator;

/**
 * Jobs Model
 *
 * @property \App\Model\Table\JobTypesTable&\Cake\ORM\Association\BelongsTo $JobTypes
 * @property \App\Model\Table\JobStatusTable&\Cake\ORM\Association\BelongsTo $JobStatus
 * @property \App\Model\Table\UsersTable&\Cake\ORM\Association\BelongsTo $Users
 * @property \App\Model\Table\ProductsTable&\Cake\ORM\Association\BelongsTo $Products
 * @property \App\Model\Table\CustomersTable&\Cake\ORM\Association\BelongsTo $Customers
 * @property \App\Model\Table\UsersTable&\Cake\ORM\Association\BelongsToMany $Users
 *
 * @method \App\Model\Entity\Job newEmptyEntity()
 * @method \App\Model\Entity\Job newEntity(array $data, array $options = [])
 * @method \App\Model\Entity\Job[] newEntities(array $data, array $options = [])
 * @method \App\Model\Entity\Job get($primaryKey, $options = [])
 * @method \App\Model\Entity\Job findOrCreate($search, ?callable $callback = null, $options = [])
 * @method \App\Model\Entity\Job patchEntity(\Cake\Datasource\EntityInterface $entity, array $data, array $options = [])
 * @method \App\Model\Entity\Job[] patchEntities(iterable $entities, array $data, array $options = [])
 * @method \App\Model\Entity\Job|false save(\Cake\Datasource\EntityInterface $entity, $options = [])
 * @method \App\Model\Entity\Job saveOrFail(\Cake\Datasource\EntityInterface $entity, $options = [])
 * @method \App\Model\Entity\Job[]|\Cake\Datasource\ResultSetInterface|false saveMany(iterable $entities, $options = [])
 * @method \App\Model\Entity\Job[]|\Cake\Datasource\ResultSetInterface saveManyOrFail(iterable $entities, $options = [])
 * @method \App\Model\Entity\Job[]|\Cake\Datasource\ResultSetInterface|false deleteMany(iterable $entities, $options = [])
 * @method \App\Model\Entity\Job[]|\Cake\Datasource\ResultSetInterface deleteManyOrFail(iterable $entities, $options = [])
 *
 * @mixin \Cake\ORM\Behavior\TimestampBehavior
 */
class JobsTable extends Table
{
    /**
     * Initialize method
     *
     * @param array $config The configuration for the Table.
     * @return void
     */
    public function initialize(array $config): void
    {
        parent::initialize($config);

        $this->setTable('jobs');
        $this->setDisplayField('id');
        $this->setPrimaryKey('id');

        $this->addBehavior('Timestamp');

        $this->hasOne('Images', [
            'className' =>  'Contents',
            'foreignKey' => 'model_id',
            'conditions'    =>  array(
                'Images.model'    =>    'Job',
                'Images.type'   =>  'image'
            )
        ]);

        $this->belongsTo('JobTypes', [
            'foreignKey' => 'job_type_id',
        ]);
        $this->belongsTo('JobStatuses', [
            'foreignKey' => 'job_status_id',
        ]);
        $this->belongsTo('Users', [
            'foreignKey' => 'user_id',
        ]);
        $this->belongsTo('Products', [
            'foreignKey' => 'product_id',
        ]);
        $this->belongsTo('Services', [
            'foreignKey' => 'service_id',
        ]);
        $this->belongsTo('Customers', [
            'foreignKey' => 'customer_id',
        ]);
        $this->belongsToMany('Employes', [
            'foreignKey' => 'job_id',
            'targetForeignKey' => 'employee_id',
            'joinTable' => 'jobs_users',
        ]);
    }

    /**
     * Default validation rules.
     *
     * @param \Cake\Validation\Validator $validator Validator instance.
     * @return \Cake\Validation\Validator
     */
    public function validationDefault(Validator $validator): Validator
    {
        $validator
            ->integer('id')
            ->allowEmptyString('id', null, 'create');

        $validator
            ->integer('is_urgent')
            ->allowEmptyString('is_urgent');


        return $validator;
    }

    /**
     * Returns a rules checker object that will be used for validating
     * application integrity.
     *
     * @param \Cake\ORM\RulesChecker $rules The rules object to be modified.
     * @return \Cake\ORM\RulesChecker
     */
    public function buildRules(RulesChecker $rules): RulesChecker
    {
        $rules->add($rules->existsIn(['job_type_id'], 'JobTypes'), ['errorField' => 'job_type_id']);
        $rules->add($rules->existsIn(['job_status_id'], 'JobStatuses'), ['errorField' => 'job_status_id']);
        $rules->add($rules->existsIn(['user_id'], 'Users'), ['errorField' => 'user_id']);
        $rules->add($rules->existsIn(['product_id'], 'Products'), ['errorField' => 'product_id']);
        $rules->add($rules->existsIn(['customer_id'], 'Customers'), ['errorField' => 'customer_id']);

        return $rules;
    }
}

templates/Jobs/edit.php
<?php
/**
 * @var \App\View\AppView $this
 * @var \App\Model\Entity\User $user
 */
?>
<?php
    // configure breadcrumb
    // $this->Breadcrumbs->setTemplates();

    $this->Breadcrumbs->add(
        '&nbsp;',
        ['controller' => 'dashboards', 'action' => 'index'],
        [
            'class' =>  'm-nav__item m-nav__item--home',
            'innerAttrs'    =>  [
                'class' =>  'm-nav__link m-nav__link--icon'
            ],
            'templateVars'  =>  [
                'beforeTitle'  =>  '<i class="m-nav__link-icon la la-home"></i>'
            ]
        ]
    );

    $this->Breadcrumbs->add(
        $actionTitle . " List",
        ['controller' => 'users', 'action' => 'index'],
        [
            'class' =>  'm-nav__item',
            'innerAttrs'    =>  [
                'class' =>  'm-nav__link'
            ],
            'templateVars'  =>  [
                'beforeTitle'   =>  '<span class="m-nav__link-text">',
                'afterTitle'    =>  '</span>'
            ]
        ]
    );


    $this->Breadcrumbs->add(
        $listItemTitle,
        null,
        [
            'class' =>  'm-nav__item',
            'innerAttrs'    =>  [
                'class' =>  'm-nav__link'
            ]
        ]
    );
?>

<!-- BEGIN: Subheader -->
<div class="m-subheader ">
    <div class="d-flex align-items-center">
        <div class="mr-auto">
            <h3 class="m-subheader__title m-subheader__title--separator">
                <?= h($actionTitle) ?>
            </h3>
            <?php
                echo $this->Breadcrumbs->render(
                    [],
                    [
                        'separator' =>  '-'
                    ]
                );
            ?>
        </div>
    </div>
</div>
<!-- END: Subheader -->
<div class="m-content">
    <!-- FLash Message Here -->
    <?= $this->Flash->render(); ?>

    <!--begin::Portlet-->
    <div class="m-portlet">
        <div class="m-portlet__head">
            <div class="m-portlet__head-caption">
                <div class="m-portlet__head-title">
                    <span class="m-portlet__head-icon m--hide">
                        <i class="la la-gear"></i>
                    </span>
                    <h3 class="m-portlet__head-text">
                        <?= h($listItemTitle) ?>
                    </h3>
                </div>
            </div>
        </div>
        <!--begin::Form-->
        <?= $this->Form->create($product, ['class' =>  'm-form m-form--fit m-form--label-align-right m-form--group-seperator-dashed', 'type'   =>  'file']) ?>
        <?php
            $this->Form->setTemplates([
                'inputContainer'        => '<div class="form-group m-form__group row">{{content}}</div>',
                'inputContainerError'   => '<div class="form-group m-form__group row">{{content}}{{error}}</div>',
                'label'             => '<label class="col-lg-2 col-form-label">{{text}}</label>',
                'input'             => '<div class="col-lg-6"><input type="{{type}}" name="{{name}}"{{attrs}}/></div>',
                'select'            =>  '<div class="col-lg-6"><select name="{{name}}"{{attrs}}>{{content}}</select></div>',
                'error' => '<div class="col-lg-6"></div><div class="col-lg-6"><span class="m-form__help error">{{content}}</span></div>',
            ]);
        ?>
            <div class="m-portlet__body">
                <?php



                    echo $this->Form->control('name', [
                        'class' =>  'form-control m-input',
                        'placeholder'   =>  'Enter Name',
                    ]);

                    echo $this->Form->control('spec', [
                        'class' =>  'form-control m-input',
                        'placeholder'   =>  'Enter spec',
                    ]);


                    echo $this->Form->control('imagefile', [
                        'type' => 'file'
                    ]);
                ?>
            </div>
            <div class="m-portlet__foot m-portlet__no-border m-portlet__foot--fit">
                <div class="m-form__actions m-form__actions--solid">
                    <div class="row">
                        <div class="col-lg-2"></div>
                        <div class="col-lg-6">
                            <?= $this->Form->button(__('Submit'), [
                                'class' =>  'btn btn-primary'
                            ]) ?>
                        </div>
                    </div>
                </div>
            </div>
        <?= $this->Form->end() ?>
        <!--end::Form-->
    </div>
    <!--end::Portlet-->
</div>
<?php
/**
 * @var \App\View\AppView $this
 * @var \App\Model\Entity\User[]|\Cake\Collection\CollectionInterface $users
 */
?>

<?php
    $this->start('scriptBottom');
    // echo $this->Html->script("/assets/demo/default/custom/crud/metronic-datatable/base/html-table.js");
    ?>
        <script type="text/javascript">
        </script>
    <?php
    $this->end();
?>

templates/Jobs/managed_job_employee.php
<?php
    // configure breadcrumb
    // $this->Breadcrumbs->setTemplates();

    $this->Breadcrumbs->add(
        '&nbsp;',
        ['controller' => 'dashboards', 'action' => 'index'],
        [
            'class' =>  'm-nav__item m-nav__item--home',
            'innerAttrs'    =>  [
                'class' =>  'm-nav__link m-nav__link--icon'
            ],
            'templateVars'  =>  [
                'beforeTitle'  =>  '<i class="m-nav__link-icon la la-home"></i>'
            ]
        ]
    );

    $this->Breadcrumbs->add(
        $listItemTitle,
        ['controller' => 'jobs', 'action' => 'index'],
        [
            'class' =>  'm-nav__item m-nav__item--home',
            'innerAttrs'    =>  [
                'class' =>  'm-nav__link m-nav__link--icon'
            ],
            'templateVars'  =>  [
                // 'beforeTitle'  =>  '<i class="m-nav__link-icon la la-home"></i>'
            ]
        ]
    );

    $this->Breadcrumbs->add(
        $data->job_type_with_product_name,
        null,
        [
            'class' =>  'm-nav__item',
            'innerAttrs'    =>  [
                'class' =>  'm-nav__link'
            ]
        ]
    );
?>
<style>
      .card {
      z-index: 0;
      background-color: #ECEFF1;
      padding-bottom: 20px;
      border-radius: 10px
      }

      .top {
        padding-top: 10px;
        padding-left: 7% !important;
        padding-right: 18% !important;
      }
      .top p {
        float: left;
        margin-left: -70px;
        margin-top: 70px;
      }
      #progressbar {
      margin-bottom: 30px;
      overflow: hidden;
      color: #455A64;
      padding-left: 0px;
      margin-top: 30px
      }

      #progressbar li {
      list-style-type: none;
      font-size: 13px;
      width: 15%;
      float: left;
      position: relative;
      font-weight: 400
      }

      #progressbar .step0:before {
      font-family: FontAwesome;
      content: "\f10c";
      color: #fff
      }

      #progressbar li:before {
      width: 40px;
      height: 40px;
      line-height: 45px;
      display: block;
      font-size: 20px;
      background: #C5CAE9;
      border-radius: 50%;
      margin: auto;
      padding: 0px
      }

      #progressbar li:after {
      content: '';
      width: 100%;
      height: 12px;
      background: #C5CAE9;
      position: absolute;
      left: 0;
      top: 16px;
      z-index: -1
      }

      #progressbar li:last-child:after {
      border-top-right-radius: 10px;
      border-bottom-right-radius: 10px;
      position: absolute;
      left: -50%
      }

      #progressbar li:nth-child(2):after,
      #progressbar li:nth-child(3):after,
      #progressbar li:nth-child(4):after,
      #progressbar li:nth-child(5):after {
      left: -50%
      }

      #progressbar li:first-child:after {
      border-top-left-radius: 10px;
      border-bottom-left-radius: 10px;
      position: absolute;
      left: 50%
      }

      #progressbar li:last-child:after {
      border-top-right-radius: 10px;
      border-bottom-right-radius: 10px
      }

      #progressbar li:first-child:after {
      border-top-left-radius: 10px;
      border-bottom-left-radius: 10px
      }

      #progressbar li.active:before,
      #progressbar li.active:after {
      background-color: #651FFF
      /* transition: 0.5s ease; */
      }

      #progressbar li.active:before {
      font-family: FontAwesome;
      content: "\f00c"
      }

      .icon {
      width: 60px;
      height: 60px;
      margin-right: 15px
      }

      .icon-content {
      padding-bottom: 20px

      }

      @media screen and (max-width: 992px) {
      .icon-content {
          width: 50%
      }
      }
      #center{
        margin-left: 50px;
      }
</style>
<!-- BEGIN: Subheader -->
<div class="m-subheader ">
    <div class="d-flex align-items-center">
        <div class="mr-auto">
            <h3 class="m-subheader__title m-subheader__title--separator">
                <?= h($actionTitle) ?>
            </h3>
            <?php
                echo $this->Breadcrumbs->render(
                    [],
                    [
                        'separator' =>  '-'
                    ]
                );
            ?>
        </div>
    </div>
</div>
<!-- END: Subheader -->
<div class="m-content">
    <div class="row">
      <div class="col-xl-12">
          <!--begin:: Widgets/Company Summary-->
          <div class="m-portlet m-portlet--full-height ">
              <div class="m-portlet__head">
                  <div class="m-portlet__head-caption">
                      <div class="m-portlet__head-title">
                          <h3 class="m-portlet__head-text">
                              Job Tracking
                          </h3>
                      </div>
                  </div>
              </div>
              <div class="m-portlet__body">
                  <div class="m-widget13">
                    <div class="card">

          <div class="row d-flex justify-content-between px-3 top">
              <div class="d-flex">
                  <h5>Track Job For Customer <span class="text-primary font-weight-bold"><?= h($data->customer->name) ?></span></h5>
              </div>
            
          </div> <!-- Add class 'active' to progress -->
          <div id="center">
            <div class="row d-flex justify-content-center">
                <div class="col-12" id="status">
                    <ul id="progressbar" class="text-center">
                        <li id="step0" class="active step0"></li>
                        <li id="step1" class=" step0"></li>
                        <li id="step2" class=" step0"></li>
                        <li id="step3" class=" step0"></li>
                        <li id="step4" class=" step0"></li>
                        <li id="step5" class=" step0"></li>

                    </ul>
                </div>
            </div>
    <div class="row justify-content-between top">
                <div class="row d-flex icon-content"> <img class="icon" src="/assets/created.png">
                    <div class="d-flex flex-column">
                        <p class="font-weight-bold">Job<br>Created</p>
                    </div>
                </div>
                <div class="row d-flex icon-content"> <img class="icon" src="/assets/confirmed.png">
                    <div class="d-flex flex-column">
                        <p class="font-weight-bold">Job<br>Confirmed</p>
                    </div>
                </div>
                <div class="row d-flex icon-content"> <img class="icon" src="/assets/on-progress.png">
                    <div class="d-flex flex-column">
                        <p class="font-weight-bold">Job<br>On Progrees</p>
                    </div>
                </div>
                <div class="row d-flex icon-content"> <img class="icon" src="/assets/on-hold.png">
                    <div class="d-flex flex-column">
                        <p class="font-weight-bold">Job<br>On Hold</p>
                    </div>
                </div>
                <div class="row d-flex icon-content"> <img class="icon" src="/assets/cancelled.png">
                    <div class="d-flex flex-column">
                        <p class="font-weight-bold">Job<br>Cancelled</p>
                    </div>
                </div>
                <div class="row d-flex icon-content"> <img class="icon" src="/assets/completed.png">
                    <div class="d-flex flex-column">
                        <p class="font-weight-bold">Job<br>Comleted</p>
                    </div>
                </div>
            </div>
          </div>


      </div>
       <div class="col-xl-12">
            <!--begin:: Widgets/Company Summary-->
            <div class="m-portlet m-portlet--full-height ">
                <div class="m-portlet__head">
                    <div class="m-portlet__head-caption">
                        <div class="m-portlet__head-title">
                            <h3 class="m-portlet__head-text">
                                Job Summary
                            </h3>
                        </div>
                    </div>
                </div>
                <div class="m-portlet__body">
                    <div class="m-widget13">

                        <div class="m-widget13__item">
                            <span class="m-widget13__desc m--align-left">
                                Job Type
                            </span>
                            <span class="m-widget13__text m-widget13__text-bolder">
                                <?= h($data->job_type->name) ?>
                            </span>
                        </div>
                        <div class="m-widget13__item">
                            <span class="m-widget13__desc m--align-left">
                                Job Status
                            </span>
                            <!-- <span class="m-widget13__text m-widget13__text-bolder">
                                <?= h($data->job_status->name) ?>
                            </span> -->
                            <span class="m-widget13__text m-widget13__text-bolder">
                                <?= h($data->job_status->name) ?>
                            </span>
                        </div>
                        <div class="m-widget13__item">
                            <span class="m-widget13__desc m--align-left">
                                Poduct Name
                            </span>
                            <span class="m-widget13__text m-widget13__text-bolder">
                                <?= h($data->product->name) ?>
                            </span>
                        </div>
                        <div class="m-widget13__item">
                            <span class="m-widget13__desc m--align-left">
                                Service
                            </span>
                            <span class="m-widget13__text m-widget13__text-bolder">
                                <?= h($data->service->name) ?>
                            </span>
                        </div>
                        <div class="m-widget13__item">
                            <span class="m-widget13__desc m--align-left">
                                Customer Name
                            </span>
                            <span class="m-widget13__text m-widget13__text-bolder">
                                <?= h($data->customer->name) ?>
                            </span>
                        </div>
                        <div class="m-widget13__item">
                            <span class="m-widget13__desc m--align-left">
                                Customer Address
                            </span>
                            <span class="m-widget13__text m-widget13__text-bolder">
                                <?= h($data->customer->address) ?>
                            </span>
                        </div>
                        <div class="m-widget13__item">
                            <span class="m-widget13__desc m--align-left">
                                Due Dates
                            </span>
                            <span class="m-widget13__text m-widget13__text-bolder">
                                <?= h($data->date) ?>
                            </span>
                        </div>


                    </div>
                </div>
            </div>
            <!--end:: Widgets/Company Summary-->
        </div>




                    </div>
                </div>
            </div>
            <!--end:: Widgets/Company Summary-->
        </div>
    </div>
    <div class="row">
        <div class="col-xl-12">
            <?= $this->Flash->render(); ?>
            <div id="listItemContent">
                <?php echo $this->element('../Jobs/list_item_managed_employee'); ?>
            </div>
        </div>
    </div>
</div>


        <script type="text/javascript">
            function reloadListItemContent() {
                var thisHref = "/products/managed-product-service/<?php echo $data->id ?>";
                $('#listItemContent').fadeTo(300, 0);
                $('#listItemContent').load(thisHref, function() {
                    $(this).fadeTo(200, 1);
                });
            }

        </script>
        <script type="text/javascript">
        var _job_id;
        $(document).ready(function() {
          <?php
              if(isset($data->id)) {
                  ?>
                      _job_id     =   <?= $data->id ?>;
                  <?php
              }
                  ?>
          selesai();
          //console.log(_job_id)
        });

        function selesai() {
        setTimeout(function() {
          update();
          selesai();
        }, 200);
        }

        function update() {
          $.getJSON('/Jobs/getJobStatusByJobId/' + _job_id + '.json',{},function(result){
            $('#progressbar li.step0').removeClass('active');

              if( Object.keys(result.data).length > 0)
              {
                  $.each(result.data,function(key,value){

                       $('#step'+key).addClass('active');
                var test = $('#step'+key).addClass('active');
                       console.log(test);
                  });

                  //let lastElement = Object.keys(result.data)[Object.keys(result.data).length - 1];
                  console.log('naufal');
                  var tes = result.data.pop();
                  console.log(tes.name);

              }


          });
        }
        </script>