config/routes.php
<?php
/**
 * Routes configuration.
 *
 * In this file, you set up routes to your controllers and their actions.
 * Routes are very important mechanism that allows you to freely connect
 * different URLs to chosen controllers and their actions (functions).
 *
 * It's loaded within the context of `Application::routes()` method which
 * receives a `RouteBuilder` instance `$routes` as method argument.
 *
 * CakePHP(tm) : Rapid Development Framework (https://cakephp.org)
 * Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
 *
 * Licensed under The MIT License
 * For full copyright and license information, please see the LICENSE.txt
 * Redistributions of files must retain the above copyright notice.
 *
 * @copyright     Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
 * @link          https://cakephp.org CakePHP(tm) Project
 * @license       https://opensource.org/licenses/mit-license.php MIT License
 */

use Cake\Http\Middleware\CsrfProtectionMiddleware;
use Cake\Routing\Route\DashedRoute;
use Cake\Routing\RouteBuilder;

/*
 * The default class to use for all routes
 *
 * The following route classes are supplied with CakePHP and are appropriate
 * to set as the default:
 *
 * - Route
 * - InflectedRoute
 * - DashedRoute
 *
 * If no call is made to `Router::defaultRouteClass()`, the class used is
 * `Route` (`Cake\Routing\Route\Route`)
 *
 * Note that `Route` does not do any inflections on URLs which will result in
 * inconsistently cased URLs when used with `:plugin`, `:controller` and
 * `:action` markers.
 */
/** @var \Cake\Routing\RouteBuilder $routes */
$routes->setRouteClass(DashedRoute::class);

$routes->scope('/', function (RouteBuilder $builder) {
    // Register scoped middleware for in scopes.
    // $builder->registerMiddleware('csrf', new CsrfProtectionMiddleware([
    //     'httponly' => true,
    // ]));

    /*
     * Apply a middleware to the current route scope.
     * Requires middleware to be registered through `Application::routes()` with `registerMiddleware()`
     */
    // kita gunain csrf di Application.php
    // $builder->applyMiddleware('csrf');

    /*
     * Here, we are connecting '/' (base path) to a controller called 'Pages',
     * its action called 'display', and we pass a param to select the view file
     * to use (in this case, templates/Pages/home.php)...
     */
    // $builder->connect('/', ['controller' => 'Pages', 'action' => 'display', 'home']);
    $builder->connect('/', ['controller' => 'Dashboards', 'action' => 'index', 'home']);

    /*
     * ...and connect the rest of 'Pages' controller's URLs.
     */
    $builder->connect('/pages/*', ['controller' => 'Pages', 'action' => 'display']);

    /*
     * Connect catchall routes for all controllers.
     *
     * The `fallbacks` method is a shortcut for
     *
     * ```
     * $builder->connect('/:controller', ['action' => 'index']);
     * $builder->connect('/:controller/:action/*', []);
     * ```
     *
     * You can remove these routes once you've connected the
     * routes you want in your application.
     */
    
    $builder->setExtensions(['json', 'xml']);

    $builder->fallbacks();
});

/*
 * If you need a different set of middleware or none at all,
 * open new scope and define routes there.
 *
 * ```
 * $routes->scope('/api', function (RouteBuilder $builder) {
 *     // No $builder->applyMiddleware() here.
 *     // Connect API actions here.
 * });
 * ```
 */

src/Model/Table/UsersTable.php
<?php
declare(strict_types=1);

namespace App\Model\Table;

use Cake\ORM\Query;
use Cake\ORM\RulesChecker;
use Cake\ORM\Table;
use Cake\Validation\Validator;

/**
 * Users Model
 *
 * @property \App\Model\Table\ArosTable&\Cake\ORM\Association\BelongsTo $Aros
 * @property \App\Model\Table\EmployesTable&\Cake\ORM\Association\HasMany $Employes
 *
 * @method \App\Model\Entity\User newEmptyEntity()
 * @method \App\Model\Entity\User newEntity(array $data, array $options = [])
 * @method \App\Model\Entity\User[] newEntities(array $data, array $options = [])
 * @method \App\Model\Entity\User get($primaryKey, $options = [])
 * @method \App\Model\Entity\User findOrCreate($search, ?callable $callback = null, $options = [])
 * @method \App\Model\Entity\User patchEntity(\Cake\Datasource\EntityInterface $entity, array $data, array $options = [])
 * @method \App\Model\Entity\User[] patchEntities(iterable $entities, array $data, array $options = [])
 * @method \App\Model\Entity\User|false save(\Cake\Datasource\EntityInterface $entity, $options = [])
 * @method \App\Model\Entity\User saveOrFail(\Cake\Datasource\EntityInterface $entity, $options = [])
 * @method \App\Model\Entity\User[]|\Cake\Datasource\ResultSetInterface|false saveMany(iterable $entities, $options = [])
 * @method \App\Model\Entity\User[]|\Cake\Datasource\ResultSetInterface saveManyOrFail(iterable $entities, $options = [])
 * @method \App\Model\Entity\User[]|\Cake\Datasource\ResultSetInterface|false deleteMany(iterable $entities, $options = [])
 * @method \App\Model\Entity\User[]|\Cake\Datasource\ResultSetInterface deleteManyOrFail(iterable $entities, $options = [])
 *
 * @mixin \Cake\ORM\Behavior\TimestampBehavior
 */
class UsersTable extends Table
{
    /**
     * Initialize method
     *
     * @param array $config The configuration for the Table.
     * @return void
     */
    public function initialize(array $config): void
    {
        parent::initialize($config);

        $this->setTable('users');
        $this->setDisplayField('id');
        $this->setPrimaryKey('id');

        $this->addBehavior('Timestamp');

        $this->belongsTo('Aros', [
            'foreignKey' => 'aro_id',
        ]);
        $this->hasOne('Employes', [
            'foreignKey' => 'user_id',
        ]);
        $this->hasMany('Jobs', [
            'foreignKey' => 'user_id',
        ]);

        $this->hasOne('Thumbs', [
            'className' =>  'Contents',
            'foreignKey' => 'model_id',
            'conditions'    =>  array(
                'Thumbs.model'    =>    'User',
                'Thumbs.type'   =>  'thumb'
            )
        ]);

        $this->belongsTo('Aros')->setForeignKey('aro_id');


        // add counter cache behavior to Aros table.
        $this->addBehavior('CounterCache', [
            'Aros' => ['total_admin']
        ]);
    }

    /**
     * Default validation rules.
     *
     * @param \Cake\Validation\Validator $validator Validator instance.
     * @return \Cake\Validation\Validator
     */
    public function validationDefault(Validator $validator): Validator
    {
        $validator
            ->integer('id')
            ->allowEmptyString('id', null, 'create');

        $validator
            ->email('email')
            ->requirePresence('email', 'create')
            ->notEmptyString('email');

            $validator
              ->scalar('password')
              ->minLength('password', 8, __("Minimum length is 8 characters"))
              ->maxLength('password', 255)
              ->requirePresence('password', 'create')
              ->notEmptyString('password');

        return $validator;
    }

    /**
     * Returns a rules checker object that will be used for validating
     * application integrity.
     *
     * @param \Cake\ORM\RulesChecker $rules The rules object to be modified.
     * @return \Cake\ORM\RulesChecker
     */
    public function buildRules(RulesChecker $rules): RulesChecker
    {
        $rules->add($rules->isUnique(['email']), ['errorField' => 'email']);
        $rules->add($rules->existsIn(['aro_id'], 'Aros'), ['errorField' => 'aro_id']);

        return $rules;
    }
}

src/Controller/UsersController.php
<?php
declare(strict_types=1);

namespace App\Controller;

use Cake\Cache\Cache; // For cache system engine
use Cake\Core\App;

/**
 * Users Controller
 *
 * @property \App\Model\Table\UsersTable $Users
 * @method \App\Model\Entity\User[]|\Cake\Datasource\ResultSetInterface paginate($object = null, array $settings = [])
 */
class UsersController extends AppController
{

    public $paginate = [
        'order' => [
            'Users.id' => 'desc'
        ],
        'sortableFields' =>  [
            'Users.id', 'Aros.alias', 'Users.email', 'Users.created', 'Users.status'
        ]
    ];

    public function initialize(): void
    {
        parent::initialize();
        $this->loadComponent("General");

        // using metronic layout.
        $this->viewBuilder()->setLayout('metronic_main');
    }

    public function beforeFilter(\Cake\Event\EventInterface $event)
    {
        parent::beforeFilter($event);
        // Configure the login action to not require authentication, preventing
        // the infinite redirect loop issue
        $this->Authentication->addUnauthenticatedActions(['login', 'add']);
        $this->set('activeParentMenuId', 3);

        // contoh untuk menggunakan generalComponent ResizeImageContent
        // $this->viewBuilder()->setLayout('ajax');
        // $this->General->ResizeImageContent("/Library/WebServer/Documents/latihan/cake4/cms/webroot/img/scarjo.jpg", "http://www.acisapp.xyz/", "1", "User", "thumb", "image/jpeg", 150, 150, "cropResize", "namafile");
    }

    /**
     * Index method
     *
     * @return \Cake\Http\Response|null|void Renders view
     */
    public function index()
    {
        $this->Authorization->authorize($this->Users->newEmptyEntity(), 'read');

        $this->request->allowMethod(['get']);

        $settings   =   array();

        if ($this->request->is('get')) {

            $finderSettings = array();

            if($this->request->getQuery('email') !== null && $this->request->getQuery('email') != "") { // we cannot use isset. so instead using !== null
                $finderSettings['Users.email LIKE'] =   "%" . $this->request->getQuery('email') . "%";
            }

            if($this->request->getQuery('aro_id') !== null && $this->request->getQuery('aro_id') != "") { // we cannot use isset. so instead using !== null
                $finderSettings['Users.aro_id'] =   $this->request->getQuery('aro_id');
            }
        }

        $this->paginate = [
            'order' => [
                'Users.id' => 'desc'
            ],
            'sortableFields' =>  [
                'Users.id', 'Aros.alias', 'Users.email', 'Users.created', 'Users.status'
            ],
            'limit' =>  20
        ];

        $settings   =   array_merge($settings, $finderSettings);

        $users = $this->Users->find('all', array(
            'conditions'    =>  $settings,
            'contain'       =>  ['Aros', 'Employes', 'Thumbs'],
        ));

        $arosList   =   $this->Users->Aros->find('treeList', [
            'conditions'    =>  [
                'id !=' =>  1 // 1 untuk developer
            ],
            'valuePath'   =>  'alias',
            'keyPath' =>  'id'
        ]);
        // $companyList   =   $this->Users->Companies->find('list', [
        //     'keyField' => 'id',
        //     'valueField' => 'name'
        // ]);
        $this->set(compact('users', 'arosList'));

        if ($this->request->is('ajax')) {
            $this->viewBuilder()->setLayout('ajax');
            $this->render('listItem');
        } else if($this->request->is('get') && $this->request->getQuery('excel') != null && $this->request->getQuery('excel') == 1) {

            $this->viewBuilder()->setLayout('ajax');
            $this->set('filename', $this->actionTitle . "_list.xlsx");
            $this->render('listItemExcel');

        }
    }

    /**
     * ListItem method
     *
     * @return \Cake\Http\Response|null|void Renders view
     */
    // public function listItem()
    // {
    //     $this->Authorization->authorize($this->Users->newEmptyEntity(), 'read');

    //     $this->viewBuilder()->setLayout('ajax');

    //     $users = $this->paginate($this->Users);

    //     $this->set(compact('users'));
    // }

    /**
     * View method
     *
     * @param string|null $id User id.
     * @return \Cake\Http\Response|null|void Renders view
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */
    public function view($id = null)
    {

        $user = $this->Users->get($id, [
            'contain' => ['Articles'],
        ]);

        $this->Authorization->authorize($user, 'read');

        $this->set(compact('user'));
    }

    /**
     * Add method
     *
     * @return \Cake\Http\Response|null|void Redirects on successful add, renders view otherwise.
     */
    public function add()
    {
        $this->Authorization->authorize($this->Users->newEmptyEntity(), 'create');

        $user = $this->Users->newEmptyEntity();
        $userInformation = $this->Users->Employes->newEmptyEntity();
        $user->employe = $userInformation;

        if ($this->request->is('post')) {
            $user = $this->Users->patchEntity($user, $this->request->getData(), [
                'associated'    =>  ['Employes']
            ]);
            // debug($user);
            // exit;
            if ($this->Users->save($user)) {

              if($user->imagefile->getError() == 0 && $user->imagefile->getSize() > 0) {
                  // doing the upload here.
                  $tmp_name  = $user->imagefile->getClientFilename();
                  $tmp       = $user->imagefile->getStream()->getMetadata('uri');
                  $mime_type = $user->imagefile->getClientMediaType();

                  $path_tmp = ROOT . DS . 'tmp' . DS . 'upload' . DS;

                  if (!is_dir($path_tmp)) {
                      mkdir($path_tmp, 0755);
                  }

                  $ext             = pathinfo($tmp_name, PATHINFO_EXTENSION);
                  $tmp_file_name   = md5(strval(time()));
                  $tmp_images1_img = $path_tmp . $tmp_file_name . "." . strtolower($ext);
                  $upload          = $user->imagefile->moveTo($tmp_images1_img);

                  $setting            =   $this->General->getSetting();

                  $resize                = $this->General->ResizeImageContent(
                      $tmp_images1_img,
                      $setting->cms_url,
                      $user->get('id'),
                      "User",
                      "thumb",
                      $mime_type,
                      200,
                      200,
                      "cropResize"
                  );

                  @unlink($tmp_images1_img);

              }
                $this->Flash->metronicSuccess(__('The user has been saved.'));

                return $this->redirect(['action' => 'index']);
            }
            $this->Flash->metronicError(__('The user could not be saved. Please, try again.'), ['params'  =>  ['code'   =>  'Code: U1']]);
        }

        $arosList   =   $this->Users->Aros->find('treeList', [
            'conditions'    =>  [
                'id !=' =>  1 // 1 untuk developer
            ],
            'valuePath'   =>  'alias',
            'keyPath' =>  'id'
        ]);
        // $companyList   =   $this->Users->Companies->find('list', [
        //     'keyField' => 'id',
        //     'valueField' => 'name'
        // ]);
        $this->listItemTitle    =   "Add new user";
        $this->set('listItemTitle', $this->listItemTitle);

        $this->set(compact('user', 'arosList','companyList'));
    }

    /**
     * Edit method
     *
     * @param string|null $id User id.
     * @return \Cake\Http\Response|null|void Redirects on successful edit, renders view otherwise.
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */
    public function edit($id = null)
    {
        $user = $this->Users->get($id, [
            'contain' => ['Employes', 'Aros', 'Thumbs'],
        ]);

        if(empty($user->employe)) {
            $userInformation = $this->Users->Employes->newEmptyEntity();
            $user->employe = $userInformation;
        }

        $this->Authorization->authorize($user, 'update');

        if ($this->request->is(['patch', 'post', 'put'])) {
            $user = $this->Users->patchEntity($user, $this->request->getData());
            // $this->viewBuilder()->setLayout('ajax');

            // debug($user->imagefile);

            if ($this->Users->save($user)) {

                // if we edit the loggedin user
                if($user->get('id') == $this->loggedInUser->id) {
                    Cache::delete('user_logged_in_cache' . $this->loggedInUser->id, 'loggedInUser');
                    Cache::write('user_logged_in_cache' . $this->loggedInUser->id, $user, 'loggedInUser');
                    $this->loggedInUser = $user;
                }

                // Process uploaded file here.
                if($user->imagefile->getError() == 0 && $user->imagefile->getSize() > 0) {
                    // doing the upload here.
                    $tmp_name  = $user->imagefile->getClientFilename();
                    $tmp       = $user->imagefile->getStream()->getMetadata('uri');
                    $mime_type = $user->imagefile->getClientMediaType();

                    $path_tmp = ROOT . DS . 'tmp' . DS . 'upload' . DS;

                    if (!is_dir($path_tmp)) {
                        mkdir($path_tmp, 0755);
                    }

                    $ext             = pathinfo($tmp_name, PATHINFO_EXTENSION);
                    $tmp_file_name   = md5(strval(time()));
                    $tmp_images1_img = $path_tmp . $tmp_file_name . "." . strtolower($ext);
                    $upload          = $user->imagefile->moveTo($tmp_images1_img);

templates/Users/add.php
<?php
/**
 * @var \App\View\AppView $this
 * @var \App\Model\Entity\User $user
 */
?>
<?php
    // configure breadcrumb
    // $this->Breadcrumbs->setTemplates();

    $this->Breadcrumbs->add(
        '&nbsp;',
        ['controller' => 'dashboards', 'action' => 'index'],
        [
            'class' =>  'm-nav__item m-nav__item--home',
            'innerAttrs'    =>  [
                'class' =>  'm-nav__link m-nav__link--icon'
            ],
            'templateVars'  =>  [
                'beforeTitle'  =>  '<i class="m-nav__link-icon la la-home"></i>'
            ]
        ]
    );

    $this->Breadcrumbs->add(
        $actionTitle . " List",
        ['controller' => 'users', 'action' => 'index'],
        [
            'class' =>  'm-nav__item',
            'innerAttrs'    =>  [
                'class' =>  'm-nav__link'
            ],
            'templateVars'  =>  [
                'beforeTitle'   =>  '<span class="m-nav__link-text">',
                'afterTitle'    =>  '</span>'
            ]
        ]
    );


    $this->Breadcrumbs->add(
        $listItemTitle,
        null,
        [
            'class' =>  'm-nav__item',
            'innerAttrs'    =>  [
                'class' =>  'm-nav__link'
            ]
        ]
    );
?>

<!-- BEGIN: Subheader -->
<div class="m-subheader ">
    <div class="d-flex align-items-center">
        <div class="mr-auto">
            <h3 class="m-subheader__title m-subheader__title--separator">
                <?= h($actionTitle) ?>
            </h3>
            <?php
                echo $this->Breadcrumbs->render(
                    [],
                    [
                        'separator' =>  '-'
                    ]
                );
            ?>
        </div>
    </div>
</div>
<!-- END: Subheader -->
<div class="m-content">
    <!-- FLash Message Here -->
    <?= $this->Flash->render(); ?>

    <!--begin::Portlet-->
    <div class="m-portlet">
        <div class="m-portlet__head">
            <div class="m-portlet__head-caption">
                <div class="m-portlet__head-title">
                    <span class="m-portlet__head-icon m--hide">
                        <i class="la la-gear"></i>
                    </span>
                    <h3 class="m-portlet__head-text">
                        <?= h($listItemTitle) ?>
                    </h3>
                </div>
            </div>
        </div>
        <!--begin::Form-->
        <?= $this->Form->create($user, ['class' =>  'm-form m-form--fit m-form--label-align-right m-form--group-seperator-dashed', 'type'   =>  'file']) ?>
        <?php
            $this->Form->setTemplates([
                'inputContainer'        => '<div class="form-group m-form__group row">{{content}}</div>',
                'inputContainerError'   => '<div class="form-group m-form__group row">{{content}}{{error}}</div>',
                'label'             => '<label class="col-lg-2 col-form-label">{{text}}</label>',
                'input'             => '<div class="col-lg-6"><input type="{{type}}" name="{{name}}"{{attrs}}/></div>',
                'select'            =>  '<div class="col-lg-6"><select name="{{name}}"{{attrs}}>{{content}}</select></div>',
                'error' => '<div class="col-lg-6"></div><div class="col-lg-6"><span class="m-form__help error">{{content}}</span></div>',
            ]);
        ?>
            <div class="m-portlet__body">
                <?php

                    echo $this->Form->control('aro_id', [
                        'label' => 'User Role',
                        'options' => $arosList,
                        'empty'   =>  'Please choose',
                        'class' =>  'custom-select form-control'
                    ]);
                    echo $this->Form->control('employe.full_name', [
                        'class' =>  'form-control m-input',
                        'placeholder'   =>  'Enter Date Full Name'
                    ]);
                    echo $this->Form->control('employe.address', [
                        'class' =>  'form-control m-input',
                        'placeholder'   =>  'Enter Date address'
                    ]);
                    echo $this->Form->control('email', [
                        'class' =>  'form-control m-input',
                        'placeholder'   =>  'Enter email',
                    ]);

                    echo $this->Form->control('password', [
                        'class' =>  'form-control m-input',
                        'type'  =>  'password',
                        'placeholder'   =>  '',
                    ]);
                    echo $this->Form->control('imagefile', [
                        'type' => 'file'
                    ]);
                ?>
            </div>
            <div class="m-portlet__foot m-portlet__no-border m-portlet__foot--fit">
                <div class="m-form__actions m-form__actions--solid">
                    <div class="row">
                        <div class="col-lg-2"></div>
                        <div class="col-lg-6">
                            <?= $this->Form->button(__('Submit'), [
                                'class' =>  'btn btn-primary'
                            ]) ?>
                        </div>
                    </div>
                </div>
            </div>
        <?= $this->Form->end() ?>
        <!--end::Form-->
    </div>
    <!--end::Portlet-->
</div>
<?php
/**
 * @var \App\View\AppView $this
 * @var \App\Model\Entity\User[]|\Cake\Collection\CollectionInterface $users
 */
?>

<?php
    $this->start('scriptBottom');
    // echo $this->Html->script("/assets/demo/default/custom/crud/metronic-datatable/base/html-table.js");
    ?>
        <script type="text/javascript">
        </script>
    <?php
    $this->end();
?>

templates/Users/list_item.php
<?= $this->Form->create(null, ['id' =>  'submitDeleteForm', 'url'   =>  '/users/deleteItems/users.json']) ?>


<div class="row" >
                      <div class="col-12">
                          <div class="card">
                              <div class="card-header">

                                  <?= $this->Form->button(__('Delete selection'), [
                        'class' =>  'btn btn-primary',
                        'id'    =>  'deleteButton'
                    ]) ?>

                              </div><!--end card-header-->

                              <div class="card-body">
                                <!-- <button type="button" class="btn btn-outline-info btn-sm waves-effect waves-light" id="sa-warning">Click me</button> -->
                                  <table id="datatable-buttons" class="table table-striped m-table" style="border-collapse: collapse; border-spacing: 0; width: 100%;">
                                      <thead>
                                      <tr>
                                        <th>
                                          <?php
                                              echo $this->Form->checkbox('check_all', [
                                                  'hiddenField'   =>  false,
                                                  'id'    =>  'check_all'
                                              ]);
                                          ?>
                                      </th>
                                          <th>ID</th>
                                          <th>Profile Pic</th>
                                          <th>Type User</th>
                                          <th>Users Email</th>
                                          <th>Created</th>
                                          <th>
                                            <?= __('Actions') ?>
                                          </th>
                                      </tr>
                                      </thead>


                                      <tbody>

                                      <?php foreach ($users as $user): ?>

          <tr scope="row">
            <td>
                            <!-- checkbox -->
                            <?php
                                echo $this->Form->checkbox('users.'.$user->id.'.is_checked', [
                                    'hiddenField'   =>  false
                                ]);
                            ?>
                        </td>
              <td><?= $this->Number->format($user->id) ?></td>
              <?php
                  $urlImage   =   "/assets/no_user_image.png";
                  if(!empty($user->thumb)) {
                      $urlImage   =   $user->thumb->host . $user->thumb->url;

                  }
              ?>
              <td><img class="m--marginless m--img-centered" src="<?=$urlImage ?>" style="width: 50px;"></td>
              <td><?= h($user->aro['alias']) ?></td>
              <td><?= h($user->email) ?></td>

              <td><?= h($user->created) ?></td>

              <td class="actions">
                  <?= $this->Html->link(__('View'), ['action' => 'view', $user->id]) ?>
                  <?= $this->Html->link(__('Edit'), ['action' => 'edit', $user->id]) ?>
                  <?= $this->Form->postLink(__('Delete'), ['action' => 'delete', $user->id], ['confirm' => __('Are you sure you want to delete # {0}?', $user->id)]) ?>
              </td>
                                      </tr>
                                        <?php endforeach; ?>
                                      </tbody>
                                  </table>
                              </div>
                          </div>
                      </div> <!-- end col -->
                  </div> <!-- end row -->
                  <script type="text/javascript">
                      $(document).ready(function() {

                          // kalau check all, semua checkbox di checked
                          $("#check_all").click(function(){
                              $('input:checkbox').not(this).prop('checked', this.checked);
                          });

                          $("#deleteButton").click(function(){

                              var $form       =   $('#submitDeleteForm'),
                                  url         =   $form.attr('action'); // url nya ambil dari url form diatas
                              var data        =   $form.serialize();

                              swal.fire(
                                  {title: "Are you sure?",
                                  text: "You won't be able to revert this!",
                                  type: "warning",
                                  showCancelButton: !0,
                                  confirmButtonText: "Yaa, Hapus saja!",
                                  cancelButtonText: "Tidak, Batalkan!",
                                  reverseButtons: !0}).then(function(e){
                                          if(typeof e.value !== 'undefined' && e.value == true) {

                                              $.ajax({
                                                type: "POST",
                                                url: url,
                                                data: data,
                                                success: function(data){
                                                  if (typeof data.status !== 'undefined' && data.status == 1) {
                                                      swal.fire("Deleted!","User berhasil di hapus.","success").then(function(e){
                                                          reloadListItemContent();
                                                      });
                                                  } else {
                                                      alert("Please try again");
                                                  }
                                                }
                                              });
                                          }else{
                                            e.dismiss === Swal.DismissReason.cancel && swal.fire("Batal", "Data User dibatalkan untuk di hapus)", "error")
                                          }
                                      }
                                  );

                          });

                          // untuk apabila mao hapus semua.
                          $("#submitDeleteForm").submit(function(event){
                              event.preventDefault();
                          });

                      });
                      function reloadListItemContent() {
                            var thisHref ="/users";;
                            $('#listItemContent').fadeTo(300, 0);
                            $('#listItemContent').load(thisHref, function() {
                                $(this).fadeTo(200, 1);
                            });
                        }
                  </script>